# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
pod 'Alamofire'

target 'MDBFlightStatus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MDBFlightStatus

  target 'MDBFlightStatusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MDBFlightStatusUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
